# Auto-report action script, 3 times a day

name: futari report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '10 0,6,12,18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pillow pytesseract requests
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        EMER_PERSON: ${{ secrets.Emer_person }}
        EMER_RELA: ${{ secrets.Emer_rela }}
        EMER_PHONE: ${{ secrets.Emer_phone }}
        STUID2: ${{ secrets.Stuid2 }}
        PASSWORD2: ${{ secrets.Password2 }}
        EMER_PERSON2: ${{ secrets.Emer_person2 }}
        EMER_RELA2: ${{ secrets.Emer_rela2 }}
        EMER_PHONE2: ${{ secrets.Emer_phone2 }}
        DORM_BUILDING: ${{ secrets.DORM_BUILDING }}
        DORM : ${{ secrets.DORM }}
      run: |
        python report.py data_atschool.json "$STUID" "$PASSWORD" "$EMER_PERSON" "$EMER_RELA" "$EMER_PHONE" "$DORM_BUILDING" "$DORM"
        python report.py data_atschool.json "$STUID2" "$PASSWORD2" "$EMER_PERSON2" "$EMER_RELA2" "$EMER_PHONE2" "$DORM_BUILDING" "$DORM"
