# Auto-report action script, 3 times a day

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '5 12,14,16,18,20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pillow pytesseract requests selenium
        wget https://chromedriver.storage.googleapis.com/102.0.5005.61/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo cp chromedriver /usr/bin
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        wget https://raw.githubusercontent.com/pipixia244/South_Seven-AutoReport/master/simsun.ttc
        wget https://raw.githubusercontent.com/pipixia244/South_Seven-AutoReport/master/simhei.ttf
        cp simsun.ttc /usr/share/fonts/
        cp simhei.ttf /usr/share/fonts/
        sudo chmod -R 755 /usr/share/fonts/
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        EMER_PERSON: ${{ secrets.Emer_person }}
        EMER_RELA: ${{ secrets.Emer_rela }}
        EMER_PHONE: ${{ secrets.Emer_phone }}
        STUID2: ${{ secrets.Stuid2 }}
        PASSWORD2: ${{ secrets.Password2 }}
        EMER_PERSON2: ${{ secrets.Emer_person2 }}
        EMER_RELA2: ${{ secrets.Emer_rela2 }}
        EMER_PHONE2: ${{ secrets.Emer_phone2 }}
        DORM_BUILDING: ${{ secrets.DORM_BUILDING }}
        DORM : ${{ secrets.DORM }}
        BIGDATA_URL : ${{ secrets.BIGDATA_URL }}
        ANKANG_URL : ${{ secrets.ANKANG_URL }}
        PHONE : ${{ secrets.PHONE }}
        ADDRESS : ${{ secrets.ADDRESS }}
      run: |
        python report.py data_atschool.json "$STUID" "$PASSWORD" "$EMER_PERSON" "$EMER_RELA" "$EMER_PHONE" "$DORM_BUILDING" "$DORM" "$BIGDATA_URL" "$ANKANG_URL" "$PHONE" "$ADDRESS"
